const ERROR_TYPES = {
    BAD_REQUEST: "BAD_REQUEST",
    ANAUTORIZED: "ANAUTORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};

module.exports = ERROR_TYPES;