
# GET http://localhost:3000/api/contacts/

# GET http://localhost:3000/api/contacts/:id

# POST http://localhost:3000/api/contacts/

# DELETE http://localhost:3000/api/contacts/:id

# PUT http://localhost:3000/api/contacts/:id









