GET http://localhost:3000/api/contacts
Accept: application/json
###

GET http://localhost:3000/api/contacts/63efd6f0b529ebf6bc279e5f
Accept: application/json
###

POST http://localhost:3000/api/contacts
Content-Type: application/json

{
  "name": "joeNOWWW",
  "email": "eeemmmaaaiiilll",
  "phone": "11111116"
}
###
POST http://localhost:3000/api/contacts
Content-Type: application/json

{
  "name": "joeNOWWW",
  "email": "examp@email.com",
  "phone": "+111111162222"
}
###


DELETE http://localhost:3000/api/contacts/63fd1f221db8f9921637e2ed
Accept: application/json
###
GET http://localhost:3000/api/contacts/63fd1f221db8f9921637e2ed
Accept: application/json
###
// todo: get by wrong id????

###
PATCH http://localhost:3000/api/contacts/63f1e79d4dc50cca4f43735b
Content-Type: application/json

{
  "phone": "+380677490000"
}
###
GET http://localhost:3000/api/contacts/63f1e79d4dc50cca4f43735b
Accept: application/json
###


PATCH http://localhost:3000/api/contacts/63f1e79d4dc50cca4f43735b/favorite
Content-Type: application/json

{
  "favorite": "true"
}