GET http://localhost:3000/api/contacts
Accept: application/json
###

GET http://localhost:3000/api/contacts/34
Accept: application/json
###

POST http://localhost:3000/api/contacts
Content-Type: application/json

{
  "name": "joe",
  "email": "eeemmmaaaiiilll",
  "phone": "11111116"
}
###
POST http://localhost:3000/api/contacts
Content-Type: application/json

{
  "name": "joeї'",
  "email": "examp@email.com",
  "phone": "+111111162222"
}
###



DELETE http://localhost:3000/api/contacts/81
Accept: application/json
###

PUT http://localhost:3000/api/contacts/2
Content-Type: application/json

{
  "phone": "+38067702270222"
}
###