

# POST http://localhost:3000/api/contacts/ HTTP/1.1
# content-type: application/json

# {
#     "name": "DaiRo Manosalva",
#     "email": "damanosalvag@gmail.com",
#     "phone": "319-7522992"
#   }

# DELETE  http://localhost:3000/api/contacts/aa5a1317-fd40-4c76-bec5-31dca78d3bf6 HTTP/1.1

PUT http://localhost:3000/api/contacts/rsKkOQUi80UsgVPCcLZZW HTTP/1.1
content-type: application/json

{
    "name": "Dairo Manosalva",
    "email": "damanosalvag@gmail.com",
    "phone": "319-7522992"
  }