const HTTP_CODES = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
}

const STATUS = {
  ERROR: 'error',
  SUCCESS: 'success',
  FAIL: 'fail',
}

const SUBSCRIPTION_TYPE = {
  STARTER: 'starter',
  PROFESSIONAL: 'pro',
  BUSINESS: 'business',
}

module.exports = { HTTP_CODES, STATUS, SUBSCRIPTION_TYPE }