const express = require("express");
const contrs = require("../../controllers/contacts");
const router = express.Router();
const valideteContBody = require("../../middlewares/valideteBody");
const schema = require("../../schemas/addContSchema");
router.get("/", contrs.getAll);
router.get("/:contactId", contrs.getById);
router.post("/", valideteContBody(schema), contrs.addCont);
router.delete("/:contactId", contrs.removeCont);
router.put("/:contactId", valideteContBody(schema), contrs.updateById);
module.exports = router;
