const LIMIT_AGE = {
  min: 18,
  max: 60,
};

const HTTP_STATUS_CODE = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  CONFLICT: 409,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
};

const MAX_REQ_BODY_SIZE = {
  LIMIT: 10000,
};

module.exports = { LIMIT_AGE, HTTP_STATUS_CODE, MAX_REQ_BODY_SIZE };
export {};
